<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE book [
	<!ELEMENT book (title,author,breakline,publisher,language)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT author (#PCDATA)>
	<!ELEMENT publisher (#PCDATA)>
	<!ELEMENT spouse (#PCDATA)>
	<!ELEMENT breakline EMPTY>
	<!ELEMENT language (#PCDATA)>
]>
<book>
	<title>web技術</title>
	<author>王曉明</author>
	<breakline />
	<publisher>旗標</publisher>
	<language>zh</language>
</book>
