<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE BookCatalogue [
<!ELEMENT BookCatalogue (Book)*>
<!ELEMENT Book (Title, Author+, ReleaseDate, ISBN?, Publisher)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT ReleaseDate (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT Publisher (Country,Company)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT Company (#PCDATA)>
<!ATTLIST Book category CDATA #REQUIRED>
<!ATTLIST Book page CDATA #REQUIRED>
<!ATTLIST Author sex (男|女|male|female) "男">
<!ATTLIST Author mail CDATA #IMPLIED>
<!ATTLIST Publisher city NMTOKEN "Taipei">
<!ATTLIST Publisher address NMTOKENS #REQUIRED>
]>
<BookCatalogue>
	<Book category="web" page="1">
		<Title>web技術</Title>
		<Author sex="male">王曉明</Author>
		<ReleaseDate>release data</ReleaseDate>
		<ISBN>192-98765-4321</ISBN>
		<Publisher city="雲林" address="632雲林縣虎尾鎮文化路64號">
			<Country>tw</Country>
			<Company>旗標</Company>
		</Publisher>
	</Book>
	<Book category="web" page="2">
		<Title>web應用</Title>
		<Author sex="male">王曉明</Author>
		<ReleaseDate>release data</ReleaseDate>
		<ISBN>192-98765-1234</ISBN>
		<Publisher city="雲林" address="632雲林縣虎尾鎮文化路64號">
			<Country>tw</Country>
			<Company>旗標</Company>
		</Publisher>
	</Book>
</BookCatalogue>
